steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['all']
  env: ['PROJECT_ROOT=github.com/Stackdriver/stackdriver-prometheus']
  entrypoint: ./go.ash
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/stackdriver-prometheus', '.']
images: ['gcr.io/$PROJECT_ID/stackdriver-prometheus']
options:
 diskSizeGb: 200
 machineType: 'N1_HIGHCPU_8'

