steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['all']
  env: ['PROJECT_ROOT=github.com/Stackdriver/stackdriver-prometheus']
  entrypoint: ./go.ash
options:
 diskSizeGb: 200
 machineType: 'N1_HIGHCPU_8'

